[package]
name = "vnt-desktop"
version = "2.0.6"
description = "VNT virtual network desktop client"
edition = "2024"
license = "Apache-2.0"

[lib]
name = "vnt_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-opener = "2"
log.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
anyhow.workspace = true
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rand = "0.10"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"

[target.'cfg(windows)'.dependencies]
runas = "1.2.0"
windows-service.workspace = true
