[package]
name = "vnt-jni"
version = "2.0.5"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
vnt-core.workspace = true

jni = "0.21"
tokio = { workspace = true, features = ["full"] }
parking_lot.workspace = true
log.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
ipnet.workspace = true
lazy_static = "1.5"
hostname.workspace = true
