[package]
name = "vnt-web"
version = "2.0.4"
edition = "2024"
license = "Apache-2.0"

[dependencies]
vnt-core.workspace = true
tokio = { workspace = true, features = ["full"] }
axum = "0.8.8"
tower-http = { version = "0.7", features = ["cors"] }
tower = { version = "0.5", features = ["util"] }

serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
log.workspace = true
ipnet.workspace = true
hostname.workspace = true
route_manager.workspace = true
toml.workspace = true
rust-embed = "8.0"
mime_guess = "2.0"
parking_lot.workspace = true
time = { workspace = true, features = ["local-offset", "formatting", "macros"] }
tokio-util.workspace = true
rand = "0.10"
