[package]
name = "vnt-ipc"
version = "2.0.4"
edition = "2024"
license = "Apache-2.0"

[dependencies]

vnt-core.workspace = true
anyhow.workspace = true
futures.workspace = true
prost.workspace = true
tokio = { workspace = true, features = ["rt", "net", "io-util", "time"] }
tokio-util.workspace = true
log.workspace = true
time.workspace = true
console = "0.16.2"
cli-table = "0.5.0"

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"
