// 组网参数说明集中维护，Web 与桌面端共用。
// 每项都包含“做什么、怎么填、何时使用”，避免表单本身被长说明淹没。
export const configHelp = {
  config_name: {
    param: "config_name",
    summary: "给这份配置起一个便于识别的名称。",
    usage: "只用于配置列表展示，不参与组网认证，也不会发送给其他节点。适合填写使用场景或设备名称。",
    format: "任意文本；可留空。",
    example: "公司网络 / 家里 NAS",
  },
  network_code: {
    param: "network_code",
    summary: "标识要加入的虚拟网络。",
    usage: "连接同一服务器且网络编号相同的节点会进入同一个虚拟网络。所有需要互通的节点必须填写一致；它不是加密密码。",
    format: "必填字符串，建议使用不易猜测且便于管理的名称。",
    example: "team-prod-net",
  },
  server: {
    param: "server",
    summary: "VNT 节点用于注册、发现对端和中继的服务器地址。",
    usage: "可以配置多个地址用于容错。支持 QUIC、TCP、WebSocket TLS 和动态 DNS TXT 发现；省略协议时默认使用 TCP。",
    format: "主机:端口（默认 tcp://）、quic://主机:端口、tcp://主机:端口、wss://域名/路径 或 dynamic://域名。",
    example: "quic://1.2.3.4:29872",
    notes: ["dynamic:// 会读取域名的 DNS TXT 记录。", "WebSocket TLS 通常使用域名和有效证书。"],
  },
  peer_address: {
    param: "peer_address",
    summary: "预先告诉本机某个 VNT 节点可能直连的公网或局域网地址。",
    usage: "适用于固定公网 IP、同一局域网或端口已映射的节点，可减少发现和打洞等待。端口必须是对端的隧道端口。",
    format: "ip:端口、域名:端口、tcp://地址:端口 或 udp://地址:端口。",
    example: "192.168.1.10:29873",
    notes: ["不带协议时会同时尝试 TCP 和 UDP。", "这不是对端的服务端口，而是 VNT 隧道端口。"],
  },
  turn: {
    param: "turn",
    summary: "指定某个目标虚拟 IP 或网段优先经过哪个节点中转。",
    usage: "用于拓扑固定、跨区域加速或禁止特定目标参与 P2P 打洞。中转节点已直连时经该节点转发；中转地址填写虚拟网关 IP 时强制走服务器中继。",
    format: "目标虚拟IP或CIDR,中转节点虚拟IP",
    example: "10.26.0.0/24,10.26.0.2",
  },
  ip: {
    param: "ip",
    summary: "请求一个固定的本机虚拟 IPv4 地址。",
    usage: "适合需要固定访问地址、路由规则或端口映射的设备。地址必须属于服务器分配的虚拟网段，并且不能与其他在线节点冲突。",
    format: "单个 IPv4 地址；留空由服务器自动分配。",
    example: "10.26.0.2",
  },
  mtu: {
    param: "mtu",
    summary: "设置虚拟网卡单个 IP 包的最大长度。",
    usage: "默认值通常适合互联网链路。遇到网页部分加载、VPN 叠加或路径分片问题时可适当调小；过小会增加包头开销。",
    format: "正整数，常用范围 1200–1500；留空使用默认值。",
    example: "1380",
  },
  tunnel_port: {
    param: "tunnel_port",
    summary: "指定本机监听 P2P 隧道的端口。",
    usage: "固定端口便于路由器端口映射、防火墙放行和配置可直连节点地址。普通客户端通常保持自动分配即可。",
    format: "0 表示自动分配，或填写可用的 1–65535 端口。",
    example: "29873",
  },
  rtx: {
    param: "rtx",
    summary: "使用带重传能力的 QUIC 增强通道降低丢包。",
    usage: "适合文件传输、远程桌面等更看重完整性的场景。弱网下吞吐通常更稳定，但重传可能带来延迟波动。",
    format: "开关；默认关闭。",
  },
  fec: {
    param: "fec",
    summary: "发送额外纠错数据，在不等待重传的情况下恢复部分丢包。",
    usage: "适合实时音视频、游戏等对延迟敏感且带宽充足的场景。会消耗额外带宽，不建议在带宽紧张的链路开启。",
    format: "开关；默认关闭。",
  },
  compress: {
    param: "compress",
    summary: "使用 LZ4 压缩隧道载荷。",
    usage: "文本、日志等可压缩流量可节省带宽；视频、压缩包和已加密流量收益很小，并会增加少量 CPU 消耗。",
    format: "开关；默认关闭。",
  },
  no_punch: {
    param: "no_punch",
    summary: "关闭自动 NAT 探测和 P2P 打洞。",
    usage: "开启后普通节点间流量主要通过服务器中继；显式配置的可直连节点地址仍会尝试直连。适用于严格防火墙或希望固定链路的环境。",
    format: "开关；默认关闭，即允许 P2P 打洞。",
  },
  no_broadcast: {
    param: "no_broadcast",
    summary: "停止把本机发出的 IPv4 广播和组播转发到虚拟网络。",
    usage: "可减少发现协议和广播风暴产生的流量；依赖局域网发现、组播服务或某些游戏联机时不要开启。",
    format: "开关；默认关闭，即允许转发。",
  },
  password: {
    param: "password",
    summary: "对虚拟网络中的节点间数据进行加密。",
    usage: "需要互通的所有节点必须使用完全相同的密码，否则无法正确通信。它独立于网络编号，建议使用高强度随机密码。",
    format: "任意非空字符串；留空表示不启用组网密码加密。",
  },
  cert_mode: {
    param: "cert_mode",
    summary: "决定连接 VNT 服务器时如何校验 TLS 证书。",
    usage: "“系统证书验证”适合有受信任域名证书的服务器；“证书指纹”适合自签名证书；“跳过验证”兼容性最好但不能确认服务器身份。",
    format: "skip、standard 或 finger。",
    notes: ["生产环境优先使用系统证书或固定指纹。", "该设置只校验服务器身份，不代替组网加密密码。"],
  },
  fingerprint: {
    param: "cert_mode = finger:…",
    summary: "固定允许连接的服务器证书 SHA-256 指纹。",
    usage: "客户端只接受与此指纹一致的服务器证书，可安全使用自签名证书。服务器更换证书后需要同步更新。",
    format: "64 位十六进制 SHA-256 指纹，不含冒号。",
    example: "3bdd8675606837cdf95d5e13445606315762315a78555f9da652940a25feaec1",
  },
  input: {
    param: "input / -i",
    summary: "把访问某个局域网 CIDR 的流量送到指定 VNT 出口节点。",
    usage: "配置在访问端，用于点对网。访问映射网段时也在这里填写映射 CIDR，并指向配置了子网映射的出口节点。重叠规则按最长前缀选择。",
    format: "目标CIDR,出口节点虚拟IP",
    example: "192.168.2.0/24,10.26.0.2",
    notes: ["出口节点还必须用 output 授权真实目标网段。", "同一 CIDR 不能同时指向不同出口节点。"],
  },
  subnet_mapping: {
    param: "subnet_mapping / --subnet-mapping",
    summary: "在出口端把访问者使用的映射地址转换成真实局域网地址。",
    usage: "用于解决访问端与目标端物理局域网网段冲突。请求目标由映射地址改为真实地址，返回来源再改回映射地址；支持 /32 子集和重叠规则，按最长前缀匹配。",
    format: "映射CIDR,真实CIDR；两侧掩码必须相同且网段不同。",
    example: "192.168.2.0/24,192.168.1.0/24",
    notes: ["此项只配置在出口端。", "真实 CIDR 必须被本机 output 完整覆盖。", "多条规则必须形成稳定的一一映射。"],
  },
  output: {
    param: "output / -o",
    summary: "允许本机作为出口节点转发到哪些真实 IPv4 网段。",
    usage: "配置在能访问目标局域网的出口端，是点对网的授权边界。只开放确实需要访问的网段；使用子网映射时这里填写映射后的真实网段。",
    format: "一个或多个 IPv4 CIDR。",
    example: "192.168.1.0/24",
    notes: ["0.0.0.0/0 会允许访问任意 IPv4 目标，使用前应评估安全风险。"],
  },
  auto_sync_subnet: {
    param: "auto_sync_subnet / --auto-sync-subnet",
    summary: "自动获取其他在线节点上报的出口子网并安装路由。",
    usage: "开启后会随节点上下线和配置变化自动增删路由；本机手动 input 规则优先。",
    format: "开关；默认关闭。",
    notes: ["不同 CIDR 即使重叠也会保留并按最长前缀匹配；CIDR 完全相同时使用虚拟 IP 最小的节点。"],
  },
  no_nat: {
    param: "no_nat",
    summary: "关闭 VNT 内置的点对网 NAT，改用操作系统转发。",
    usage: "系统转发通常性能更高，但需要自行开启 IP 转发，并配置 NAT、路由和防火墙；缺少任一项都会导致返回流量无法到达访问端。",
    format: "开关；默认关闭，即使用内置 NAT。",
  },
  device_mode: {
    param: "device_mode",
    summary: "选择 VNT 在本机创建和处理网络流量的方式。",
    usage: "tun 提供三层 IP 网络，适合大多数场景；tap 提供二层以太网，可承载 ARP 等二层帧；no 不创建虚拟网卡，仅使用端口映射等无网卡能力。",
    format: "no、tun 或 tap；默认 tun。",
    notes: ["Windows 使用 tap 时需安装 tap-windows（tap0901）驱动。", "创建 TUN/TAP 通常需要管理员权限。"],
  },
  port_mapping: {
    param: "port_mapping",
    summary: "在本机监听端口，并经指定 VNT 节点访问目标服务。",
    usage: "适合不创建虚拟网卡时访问单个 TCP/UDP 服务，也可让某个虚拟节点作为跳板访问其后方网络或域名。",
    format: "协议://本地监听地址-出口虚拟IP-最终目标地址",
    example: "tcp://0.0.0.0:81-10.0.0.2-192.168.1.10:80",
    notes: ["协议使用 tcp 或 udp。", "出口节点需要开启“允许作为映射出口”。"],
  },
  allow_mapping: {
    param: "allow_mapping",
    summary: "允许其他虚拟节点把本机用作端口映射出口。",
    usage: "开启后，其他节点可在 port_mapping 的“出口虚拟 IP”位置填写本机地址，再由本机连接最终目标。只应在受信任的虚拟网络中开启。",
    format: "开关；默认关闭。",
  },
  device_name: {
    param: "device_name",
    summary: "设置其他节点和管理页面看到的设备名称。",
    usage: "只用于识别设备，不参与路由或认证。建议使用唯一、直观的名称。",
    format: "任意文本；留空读取本机 hostname。",
    example: "office-gateway",
  },
  device_id: {
    param: "device_id",
    summary: "设置节点的稳定唯一标识。",
    usage: "通常保持自动生成。重装、迁移配置并希望服务器继续把它视为同一设备时，可保留原 ID；不同设备不能共用同一 ID。",
    format: "唯一字符串；留空自动生成。",
  },
  tun_name: {
    param: "tun_name",
    summary: "指定创建或使用的虚拟网卡名称。",
    usage: "用于脚本、路由规则或多实例场景中稳定识别网卡。名称受操作系统限制；TAP 模式下可用于选择已有适配器。",
    format: "操作系统支持的网卡名称；留空自动选择。",
    example: "vnt-tun",
  },
  outbound_interface: {
    param: "outbound_interface",
    summary: "把 VNT 的外部通信绑定到指定物理网卡。",
    usage: "服务端连接、P2P 打洞和转发流量都会使用该网卡。适合同时有 Wi-Fi、以太网或多条上联网路的主机。",
    format: "操作系统中的网卡名称；留空由系统路由决定。",
    example: "Ethernet / Wi-Fi / eth0",
  },
  event_script: {
    param: "event_script",
    summary: "在网络状态变化时调用外部脚本。",
    usage: "可用于自动更新路由、防火墙、DNS 或通知。事件名和相关数据会作为命令行参数传入脚本。",
    format: "可执行脚本的路径或命令；留空不触发。",
    example: "C:\\scripts\\vnt-event.bat",
    notes: ["事件包括 netcard-created、disconnected、reconnected 和 ip-updated。", "脚本由 VNT 进程权限运行，请确保来源可信。"],
  },
  udp_stun: {
    param: "udp_stun",
    summary: "自定义用于 UDP NAT 探测和打洞的 STUN 服务器。",
    usage: "默认服务器在当前网络不可达或希望使用自建服务时配置多个地址。错误或高延迟的地址可能降低 P2P 建连成功率。",
    format: "主机:端口；可配置多项，留空使用内置默认列表。",
    example: "stun.l.google.com:19302",
  },
  tcp_stun: {
    param: "tcp_stun",
    summary: "自定义用于 TCP NAT 探测和打洞的 STUN 服务器。",
    usage: "用于评估 TCP 映射并辅助直连。应选择支持 TCP 且网络可达的 STUN 服务，UDP STUN 地址不能直接假定支持 TCP。",
    format: "主机:端口；可配置多项，留空使用内置默认列表。",
    example: "stun.nextcloud.com:443",
  },
};
